name = "cra"
type = "webpack"
workers_dev = true
route = ""
account_id = "691a3156e374317f2c626559557a6f12"
zone_id = "cd7d068de3012345da9420df9514dad0"

[site]
bucket = "./build"
entry-point = "workers-site"
